config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  root 'car_parks#index'

  resources :car_parks, as: 'ar_car_park' do
   resources :comments, module: :car_parks
   resources :reservations, only: [:new, :create, :edit, :update] do
     collection do
       get 'owner_index'
     end
   end
  end

  resources :reservations, only: [:index, :destroy]

  resources :car_parks, as: 'ar_car_parks', only: :index do
    resources :comments, module: :car_parks, only: :index
  end

  resources :comments do
    resources :comments, module: :comments
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :user
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, optional: true, class_name: 'Comment'
  has_many :comments, foreign_key: :parent_id, dependent: :destroy

  has_rich_text :body

  validates :body, presence: true

  after_create_commit do
    broadcast_append_to [commentable, :comments],
                        target: "#{dom_id(parent || commentable)}_comments",
                        partial: 'comments/comment_with_replies'
  end

  after_update_commit do
    broadcast_replace_to self
  end

  after_destroy_commit do
    broadcast_remove_to self
    broadcast_action_to self, action: :remove, target: "#{dom_id(self)}_with_comments"
  end
end

app/controllers/car_parks/comments_controller.rb
module CarParks
  class CommentsController < ApplicationController
    include Commentable

    before_action :set_commentable

    private

    def set_commentable
      @commentable = CarPark::Finder.call(params[:ar_car_park_id])
    end
  end
end

app/controllers/comments/comments_controller.rb
module Comments
  class CommentsController < ApplicationController
    include Commentable

    before_action :set_commentable

    private

    def set_commentable
      @parent = Comment.find(params[:comment_id])
      @commentable = @parent.commentable
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment

  def show; end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to @comment
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.turbo_stream do
        flash.now[:success] = 'Comment was successfully deleted!'
        render turbo_stream: turbo_stream.update('flash', partial: 'shared/flash')
      end
      format.html { redirect_to @comment.commentable }
    end
  end

  private

  def set_comment
    @comment = current_user.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.erb
<%= turbo_stream_from comment %>
<%= turbo_frame_tag comment do %>
  <div class="d-flex justify-content-between">
    <div><%= comment.user.name %>:</div>
    <div class=""> <%= comment.body %></div>
    <div class="text-sm ">
      <%= link_to "Reply", "#", data: { action: "click->comment-reply#toggle" }, class: 'btn btn-primary btn-sm' %>
    </div>
    <div class="d-flex">
      <%= link_to "Edit", edit_comment_path(comment), class: 'm1-2 btn btn-secondary btn-sm' %>
      <%= button_to "Delete", comment_path(comment), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: 'btn btn-danger btn-sm' %>
    </div>
  </div>
<% end %>

app/views/comments/_comment_with_replies.html.erb
<%= turbo_stream_from comment, :comments %>

<div class="ps-3 mt-3 border-start border-warning" id="<%= dom_id(comment) %>_with_comments" data-controller="comment-reply">
  <%= render comment %>

<!--  <div class="text-sm ">-->
    <%#= link_to "Reply", "#", data: { action: "click->comment-reply#toggle" }, class: 'btn btn-primary btn-sm' %>
<!--  </div>-->

  <div id="<%= dom_id(comment) %>_comments">
    <%= render partial: "comments/form", locals: { commentable: comment, comment: Comment.new, data: { comment_reply_target: "form" }, class: "d-none" } %>
    <%= render partial: "comments/comment_with_replies", collection: comment.comments, as: :comment %>
  </div>
</div>

app/views/comments/_form.html.erb
<% model = [local_assigns[:commentable], comment].compact %>
<%= form_with model: model,
              id: dom_id_for_records(*model),
              data: local_assigns[:data],
              class: ["my-2"] + Array.wrap(local_assigns[:class]) do |form| %>
  <%= render 'shared/errors', object: form.object %>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.rich_text_area :body, id: "#{dom_id_for_records(*model)}_body", class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary btn-sm text-end" %>
  <hr class="mt-0">
  <%= link_to "Cancel", comment, class: "btn btn-link bnt-sm" if form.object.persisted? %>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render "form", comment: @comment %>
<% end %>

app/views/comments/show.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render @comment %>
<% end %>