config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  root 'car_parks#index'

  resources :car_parks, as: 'ar_car_park' do
   resources :comments, module: :car_parks
   resources :reservations, only: [:new, :create, :edit, :update] do
     collection do
       get 'owner_index'
     end
   end
  end

  resources :reservations, only: [:index, :destroy]

  resources :car_parks, as: 'ar_car_parks', only: :index do
    resources :comments, module: :car_parks, only: :index
  end

  resources :comments do
    resources :comments, module: :comments
  end

end

app/views/shared/_errors.html.erb
<% if object.errors&.full_messages&.any? %>
  <div class="alert alert-danger">
     <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div data-controller="flash" class="alert <%= bootstrap_class_for(key) %> alert-dismissible fade show">
    <%= content_tag :div, message %>
    <button type="button" data-action="flash#dismiss" class="btn-close"></button>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<header class="p-2 bg-dark text-white">
  <div class="container">
    <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <ul class="nav col-12 col-lg-auto mb-2 me-lg-auto justify-content-center mb-md-0">
        <li><%= link_to image_tag("nav_parking_sign.jpeg", size: "40", class: "rounded"), root_path, title: 'Home page', class: 'navbar-brand px-2' %></li>
        <li><%= link_to 'Home', root_path , class: 'nav-link px-2 text-white' %></li>
        <li><%= link_to 'Bookings', reservations_path, class: 'nav-link px-2 text-white' %></li>
     </ul>

      <div class="d-flex">
        <%= form_with url: root_path, method: :get, data: { turbo_frame: 'search-results',
                                                           turbo_action: 'advance',
                                                           controller: 'search',
                                                           action: 'input->search#submit' } do %>
          <%= text_field_tag 'address_search', nil, placeholder: 'Type parking address or title', class: 'form-control' %>
        <% end %>
      </div>


      <ul class="nav-bar nav col-12 col-lg-auto mb-2 mb-md-0">
        <% if user_signed_in? %>

          <li class="dropdown">
            <%= link_to '#', class: 'nav-link text-white px-2 dropdown-toggle', data: {"bs-toggle": 'dropdown'} do %>
              <%= current_user.gravatar %>
              <%= current_user.name_with_role %>
            <% end %>

            <ul class="dropdown-menu dropdown-menu-dark">
              <li><%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link text-white' %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, class: 'nav-link text-white', data: {turbo_method: :delete} %></li>
            </ul>
          </li>

        <% else %>
          <li class="nav-link px-2"><%= link_to 'Log in', new_user_session_path, class: 'btn btn-warning btn-sm' %></li>
          <li class="nav-link px-2"><%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-warning btn-sm' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>