config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  root 'car_parks#index'

  resources :car_parks, as: 'ar_car_park' do
   resources :comments, module: :car_parks
   resources :reservations, only: [:new, :create, :edit, :update] do
     collection do
       get 'owner_index'
     end
   end
  end

  resources :reservations, only: [:index, :destroy]

  resources :car_parks, as: 'ar_car_parks', only: :index do
    resources :comments, module: :car_parks, only: :index
  end

  resources :comments do
    resources :comments, module: :comments
  end

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :car_park, class_name: 'Ar::CarPark'

  validates :start_date, :end_date, presence: true, availability: true
  validate :end_date_after_start_date
  validate :start_date_before_today
  validate :booking_period_30_days
  validate :end_day_after_unavailable_day

  scope :current_reservations, -> { where('end_date >= ?', Time.now) }
  scope :past_reservations, -> { where('end_date < ?', Time.now) }
  scope :owner_list, lambda { |user|
    select('users.email, car_park.user_id, reservations.car_park_id, reservations.start_date, reservations.end_date')
      .joins(:car_park, :user).where(car_park: { user_id: user.id }).includes([:user])
  }

  def self.available_range
    min_day..max_day
  end

  def self.min_day
    Date.today
  end

  def self.max_day
    min_day + 2.months
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, 'must be after the start date') if end_date < start_date
  end

  def start_date_before_today
    return if end_date.blank? || start_date.blank?

    errors.add(:start_date, ' must not be before today') if start_date < Date.today
  end

  def booking_period_30_days
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, 'is too far away. Booking period must be less than 30 days') if (end_date - start_date) >= 30
  end

  def end_day_after_unavailable_day
    return if end_date.blank? || start_date.blank?

    return unless car_park.unavailable_dates.find { |date| (start_date..end_date).include?(date) }

    errors.add(:base, 'The booking range must not include unavailable days.')
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[edit update show destroy]
  before_action :set_car_park, only: %i[new create owner_index]

  def new
    @reservation = Reservation.new
    @pagy_a, @available_reservations = pagy_array(Reservation.available_range.to_a, items: 21)
  end

  def owner_index
    @reservations = @car_park.reservations
  end

  def index
    if current_user&.owner_role?
      @current_reservations = Reservation.owner_list(current_user).current_reservations
      @past_reservations = Reservation.owner_list(current_user).past_reservations.limit(20)
    else
      @current_reservations = current_user.reservations.current_reservations
      @past_reservations = current_user.reservations.past_reservations.limit(20)
    end
  end

  def show; end

  def edit
    @pagy_a, @available_reservations = pagy_array(Reservation.available_range.to_a, items: 21)
  end

  def create
    @reservation = current_user.reservations.build(reservation_params)
    @reservation.car_park_id = params[:ar_car_park_id]

    if @reservation.save
      redirect_to action: :index
      flash[:success] = 'Reservation was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @reservation.car_park_id = @reservation.car_park.id
    if @reservation.update(reservation_params)
      redirect_to reservations_path
      flash[:success] = 'Reservation was successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @reservation.destroy
    redirect_to reservation_path
    flash[:success] = 'Reservation was successfully destroyed'
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def set_car_park
    @car_park = CarPark::Finder.call(params[:ar_car_park_id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/views/reservations/_form.html.erb
<%= simple_form_for [car_park, reservation] do |f| %>
  <%= render 'shared/errors', object: reservation %>
  <div class="row mt-2">
    <div class="col col-sm-8 rounded-3">
      <div class="hide"></div>
      <div class="space rounded-3 d-inline-flex align-items-start border-danger" >
        <%= f.text_field :start_date, label: "Dates", placeholder: "From", class: "border-secondary",
                         data: {
                             controller: "flatpickr",
                             flatpickr_min_date: Reservation.min_day,
                             flatpickr_max_date: Reservation.max_day,
                             flatpickr_disable: car_park.unavailable_dates
                         } %>

        <%= f.text_field :end_date, placeholder: "To", class: "form-control border-secondary" %>
      </div>
    </div>

    <div class="col-sm-4 costs costs-hidden m-0" data-rate="<%= car_park.usage_fee.to_json %>">
      <table class="table table-info border-secondary ">
        <tr>
          <td><span id="days">0</span> days x <%=car_park.usage_fee %> BYN</td>
          <td class="text-right"><span id="usage_fee">0</span> BYN</td>
        </tr>
        <tr>
          <td>Discount</td>
          <td class="text-right"><span id="discount"><%= car_park.discount %></span>%</td>
        </tr>
        <tr>
          <td><strong>Total</strong></td>
          <td class="text-right"><span id=total-price>0</span> BYN</td>
        </tr>
      </table>

      <div class="text-center my-2">
        <%= f.submit "Book", class: "btn btn-success" %>
      </div>
    </div>
  </div>
<% end %>


<div class="text-sm-center fs-4 text-decoration-underline my-3">
  Calendar of available parking spaces
</div>

<div class="container text-center">
  <div class="container d-inline-flex justify-content-center"><%== pagy_bootstrap_nav @pagy_a %></div>
  <% @available_reservations.each do |date| %>
    <% present(car_park, CarParkPresenter) do |car_park| %>
      <div class="d-inline-flex my-1 mx-2 w-25 text-center border border-dark rounded">
        <div class="label-date bg-dark text-white-50 bg-opacity-75 w-50 p-1"><%= date.strftime('%d %B') %></div>
        <div class="spaces border-dark border-start w-50 p-1 <%=car_park.count_style(date)[:color]%> text-s"><%= car_park.count_style(date)[:count] %></div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reservations/_reservation.html.erb
<div class="row border border-dark bg-light my-1 rounded-3">
  <div class="row col col-4 p-1 mx-2 text-truncate">
    <%= link_to "'#{ reservation.car_park.title }', #{ reservation.car_park.address }", reservations_path, class: ' btn bnt-link ' %>
  </div>
  <% if current_user&.owner_role? %>
    <div class="row col-2">
      <div class="text-sm-center text-info fst-italic"> Email </div>
      <%= reservation.user.email %>
    </div>
  <% end %>
  <div class="row col col-4 bg-white mx-2 rounded ">
    <div class="col col-5 ">
      <div class="text-sm-center text-info fst-italic"> Arrival </div>
      <%= reservation.start_date %>
    </div>
    <div class="col col-5 ">
      <div class="text-sm-center text-info fst-italic">Departure</div>
      <%= reservation.end_date %>
    </div>
  </div>
  <div class="col col-sm-1 btn-group btn ">
    <%= link_to 'Edit', edit_ar_car_park_reservation_path(reservation.car_park, reservation), class: 'btn btn-sm btn-primary' %>
    <%= link_to 'Delete', reservation_path(reservation), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-sm  btn-danger text-white' %>
  </div>
</div>

app/views/reservations/edit.html.erb
<div class="">
  <div class="text-sm-center fs-4 text-decoration-underline">
    Editing the booking date "<%= @reservation.car_park.title %>" parking
  </div>
  <div>
    <%= link_to "Back", reservations_path, class: 'btn btn-primary btn-sm mt-2' %>
  </div>
  <%= render partial: 'form', locals: { reservation: @reservation, car_park: @reservation.car_park } %>
</div>

app/views/reservations/index.html.erb
<div class="container mt-lg-3">
  <div class="row">
    <div class="col col-md-10">
      <div class="row justify-content-center text-center text-wrap fs-3 fw-bold">
          Current Reservations
      </div>

      <%= render partial: 'reservations/reservation', collection: @current_reservations&.includes([:car_park]) %>

      <div class="row justify-content-center text-center text-wrap fs-3 fw-bold">
        Past Reservations
      </div>
      <%= render partial: 'reservations/reservation', collection: @past_reservations&.includes([:car_park]) %>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="">
  <div class="text-sm-center fs-4 text-decoration-underline">
    Booking "<%= @car_park.title %>" parking
  </div>
  <div>
    <%= link_to "Back", ar_car_parks_path, class: 'btn btn-primary btn-sm mt-2' %>
  </div>

  <div class="widget-content">
    <%= render partial: 'form', locals: { reservation: @reservation, car_park: @car_park } %>
  </div>
</div>

app/views/reservations/owner_index.html.erb
<div class="container mt-lg-3">
  <div class="row">
    <div class="col col-md-8 ">

      <div class="row justify-content-center text-center text-wrap fs-3 fw-bold">
        <div class="col-8">
          <%= @car_park.title %> reservations
        </div>
      </div>

      <% @car_park.reservations.includes(:user).current_reservations.each do |res|  %>
        <div>
          <%= res.user.name %> <%= res.user.email %>
          <%= res.start_date %> <%= res.end_date %>
          <%#= res.payment_status %> <%#= res.user.status %>
        </div>
      <% end %>
    </div>
  </div>
</div>