config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  root 'car_parks#index'

  resources :car_parks, as: 'ar_car_park' do
   resources :comments, module: :car_parks
   resources :reservations, only: [:new, :create, :edit, :update] do
     collection do
       get 'owner_index'
     end
   end
  end

  resources :reservations, only: [:index, :destroy]

  resources :car_parks, as: 'ar_car_parks', only: :index do
    resources :comments, module: :car_parks, only: :index
  end

  resources :comments do
    resources :comments, module: :comments
  end

end

app/models/ar/car_park.rb
module Ar
  class CarPark < ApplicationRecord
    belongs_to :user
    has_many :comments, as: :commentable
    has_many :reservations, dependent: :destroy
    has_many :users, through: :reservations
    has_rich_text :body

    enum parking_type: {
      'Ground parking': 0,
      'Truck parking': 1,
      'Underground guarded parking': 2
    }

    validates :title, uniqueness: true, length: { in: 2..20 }
    validates :spaces, numericality: { in: 2..10_000 }
    validates :discount, numericality: { in: 0..25 }
    validates :title, :address, :parking_type, :usage_fee, :discount, :spaces, presence: true

    def self.search(params)
      return all if params[:address_search].blank?

      where('title ILIKE :input_value OR address ILIKE :input_value', { input_value:
                                                                    "%#{sanitize_sql_like(params[:address_search])}%" })
    end

    def self.date_filter(params)
      start_filter_date = Date.civil(params[:start][:year].to_i, params[:start][:month].to_i,
                                     params[:start][:day].to_i)

      end_filter_date = Date.civil(params[:end][:year].to_i, params[:end][:month].to_i,
                                   params[:end][:day].to_i)

      all.select { |cp| (cp.unavailable_dates & (start_filter_date..end_filter_date).to_a).empty? }
    end

    def unavailable_dates
      reservations.available_range.select do |day|
        count_unavailable_spaces(day) >= spaces
      end
    end

    def count_available_spaces(day)
      spaces - count_unavailable_spaces(day)
    end

    private

    def count_unavailable_spaces(day)
      overlapping_ranges(booked_ranges, day).size
    end

    def overlapping_ranges(ranges, day)
      ranges.select { |r| r.include?(day) }
    end

    def booked_ranges
      reservations.pluck(:start_date, :end_date).map { |date| date[0]..date[1] }
    end
  end
end

app/controllers/car_parks/comments_controller.rb
module CarParks
  class CommentsController < ApplicationController
    include Commentable

    before_action :set_commentable

    private

    def set_commentable
      @commentable = CarPark::Finder.call(params[:ar_car_park_id])
    end
  end
end

app/controllers/car_parks_controller.rb
class CarParksController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  before_action :set_car_park, only: %i[edit update show destroy]

  def index
    if current_user&.owner_role?
      @car_parks = current_user.car_parks
      render 'owner_index'
    else
      @car_parks = Ar::CarPark.includes([:user]).search(params)
      return if params[:start].blank? && params[:end].blank?

      @car_parks = Ar::CarPark.includes([:user]).date_filter(params)
    end
  end

  def show; end

  def new
    @car_park = Ar::CarPark.new
  end

  def edit; end

  def create
    @car_park = current_user.car_parks.build(car_park_params)
    if CarPark::Creator.call(@car_park)
      respond_to do |format|
        format.html { redirect_to ar_car_parks_path, notice: 'Car park was successfully created.' }
        format.turbo_stream { flash.now[:success] = 'Car park was successfully created!!!' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if CarPark::Updater.call(car_park_params, @car_park)
      respond_to do |format|
        format.html { redirect_to ar_car_park_path(@car_park), notice: 'Car park was successfully updated.' }
        format.turbo_stream { flash.now[:success] = 'Car park was successfully updated!' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    CarPark::Remover.call(@car_park)
    respond_to do |format|
      format.html { redirect_to ar_car_parks_path, notice: 'Car park was successfully destroyed.', status: :see_other }
      format.turbo_stream { flash.now[:notice] = 'Car park was successfully destroyed' }
    end
  end

  private

  def set_car_park
    @car_park = CarPark::Finder.call(params[:id])
  end

  def car_park_params
    params.require(:ar_car_park).permit(:title, :address, :parking_type, :usage_fee, :discount, :spaces)
  end
end

app/views/car_parks/_car_park.html.erb
<tbody>
  <% present(car_park, CarParkPresenter) do |car_park| %>
    <tr class="text-center">
      <td><%= link_to 'Book', new_ar_car_park_reservation_path(car_park), class: 'btn btn-success', data: { turbo_frame: '_top' } %></td>
      <td><%= link_to car_park.with_highlight(car_park.title, phrase), ar_car_park_path(car_park), data: { turbo_frame: '_top' } %></td>
      <td><%= car_park.with_highlight(car_park.address, phrase)%></td>
      <td><%= car_park.user.name %></td>
      <td><%= car_park.spaces %></td>
      <td><%= car_park.parking_type %></td>
      <td><%= car_park.fee_currency_byn %></td>
    </tr>
  <% end %>
</tbody>

app/views/car_parks/_form.html.erb
<%= form_with model: car_park do |form| %>
  <%= render 'shared/errors', object: car_park %>
  <div class="">
    <div class="input-group mb-3">
      <%= form.label :title, class: 'input-group-text' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="input-group mb-3">
      <%= form.label :address, class: 'input-group-text' %>
      <%= form.text_field :address, class: 'form-control' %>
    </div>

    <div class="input-group mb-3" >
      <%= form.label :parking_type, :Type, class: 'input-group-text' %>
      <%= form.select :parking_type, Ar::CarPark.parking_types.keys.map { |t| [t.titleize, t] }, {}, class: "form-select" %>
    </div>

    <div class="input-group mb-3">
      <%= form.label :count_of_spaces, class: 'input-group-text' %>
      <%= form.number_field :spaces, in: 0..10_000, class: 'form-control' %>
    </div>

    <div class="input-group mb-3">
      <%= form.label :usage_fee, class: 'input-group-text' %>
      <%= form.number_field :usage_fee, in: 0..100, class: 'form-control' %>
    </div>

    <div class="input-group mb-3">
      <%= form.label :discount, class: 'input-group-text' %>
      <%= form.number_field :discount, in: 0..25, class: 'form-control' %>
    </div>

    <div class="d-flex justify-content-end">
      <%= form.submit class: "btn btn-success mt-1 btn-sm" %>
    </div>
  </div>
<% end %>

app/views/car_parks/_owner_car_park.html.erb
<%= turbo_frame_tag parking do %>
  <% present(parking, CarParkPresenter) do |car_park| %>

    <div class="row border border-dark bg-dark my-1 rounded-3">
      <%= turbo_frame_tag dom_id(car_park, :show), class: "row" do %>
        <div class="row col col-sm-7 p-1 mx-3">
          <%= link_to "#{car_park.title}", owner_index_ar_car_park_reservations_path(car_park), class: 'text-link btn bg-warning', data: { turbo_frame: '_top' } %>
        </div>
        <div class="col btn-group btn ">
          <%= link_to 'Edit', edit_ar_car_park_path(car_park), class: 'btn btn-sm btn-primary', data: { turbo_frame: dom_id(Ar::CarPark.new) } %>
          <%= link_to 'Show', ar_car_park_path(car_park), class: 'btn btn-sm bg-info', data: { turbo_frame: dom_id(car_park, :show) } %>
          <%= link_to 'Delete', ar_car_park_path(car_park), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-sm  btn-outline-danger text-white' %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/car_parks/create.turbo_stream.erb
<%= turbo_stream.prepend('owner_car_parks', partial: 'owner_car_park', locals: { parking: @car_park }) %>
<%= turbo_stream.prepend('flash', partial: 'shared/flash') %>

app/views/car_parks/destroy.turbo_stream.erb
<%= turbo_stream.remove(@car_park) %>
<%= turbo_stream.prepend('flash', partial: 'shared/flash') %>

app/views/car_parks/driver_index.html.erb
<div class="text-center text-wrap fs-3 fw-bold bg-warning text-uppercase">
Available car parks
</div>

<table class="table table-info table-striped table-sm ">
  <tr class="text-center">
    <th></th>
    <th>Title</th>
    <th>Address</th>
    <th>Owner</th>
    <th>Spaces</th>
    <th>Parking type</th>
    <th>Usage fee, BYN</th>
  </tr>
  <%= render @car_parks %>
</table>

app/views/car_parks/edit.html.erb
<%= turbo_frame_tag dom_id(Ar::CarPark.new) do %>
  <div data-controller="car-park" data-action="turbo:submit-end->car-park#formSubmitEnd" %>>
    <div class="card border-dark p-2 mt-1 bg-primary">
      <div>
        <%= link_to "Back", '#', class: 'btn btn-secondary btn-sm mb-2' %>
      </div>
      <%= render 'form', car_park: @car_park %>
    </div>
  </div>
<% end %>

app/views/car_parks/index.html.erb
<div class="text-center text-wrap fs-3 fw-bold text-uppercase">
  Available car parks
</div>

<div class="container col col-10 ">
  <div class="row">
      <%= form_with url: root_path, method: :get, data: { turbo_frame: 'search-results',
                                                          turbo_action: 'advance',
                                                          controller: 'search',
                                                          action: 'change->search#submit' } do |f| %>
      <div class="col-6 rounded-3 text-end">Filter by free parking for a period of time
        <div class="input-group justify-content-end">
          <%= f.label :start_date, 'From:', class: 'form-label mx-2' %>
          <div id="start_date" class="">
            <%= select_date(Reservation.min_day, prefix: 'start', :order => [:day, :month, :year]) %>
          </div>
        </div>

        <div class="input-group justify-content-end">
          <%= f.label :end_date, 'To:', class: 'form-label mx-2' %>
          <div id="end_date" class="">
            <%= select_date(Reservation.max_day, prefix: 'end', :order => [:day, :month, :year]) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

    <%= turbo_frame_tag "search-results" do %>
      <%#=params.inspect %>
      <table class="table table-info table-striped table-sm ">
        <tr class="text-center">
          <th></th>
          <th>Title</th>
          <th>Address</th>
          <th>Owner</th>
          <th>Spaces</th>
          <th>Parking type</th>
          <th>Hourly fee</th>
        </tr>

        <%= render partial: 'car_park', collection: @car_parks, as: :car_park, locals: { phrase: params[:address_search] } %>
      </table>
    <% end %>

</div>

app/views/car_parks/new.html.erb
<%= turbo_frame_tag @car_park do %>
  <div data-controller="car-park" data-action="turbo:submit-end->car-park#formSubmitEnd" %>>
    <div class="card border-dark p-2 mt-1 bg-secondary">
      <div>
        <%= link_to "Back", ar_car_parks_path, class: 'btn btn-primary btn-sm mb-2' %>
      </div>
      <%= render 'form', car_park: @car_park %>
    </div>
  </div>
<% end %>

app/views/car_parks/owner_index.html.erb
<div class="container mt-lg-3">
  <div class="row">
    <div class="col col-md-8 ">
      <div class="row justify-content-center text-center text-wrap fs-3 fw-bold">
        <div class="col-8">
          <%= current_user.name %>'s parking
        </div>
        <div class="col-4 text-end ">
          <%= link_to "New parking", new_ar_car_park_path,
                      class: 'btn rounded bg-secondary text-warning',
                      data: { turbo_frame: dom_id(Ar::CarPark.new) } %>
        </div>
      </div>
      <%= turbo_frame_tag 'owner_car_parks' do %>
        <%= render partial: 'owner_car_park', collection: @car_parks, as: :parking %>
      <% end %>
    </div>
    <div class="container col cols-md-4 mt-3 row">
      <%= turbo_frame_tag Ar::CarPark.new %>
    </div>
  </div>
</div>

app/views/car_parks/show.html.erb
<%= turbo_frame_tag  dom_id(@car_park, :show) do %>
  <% present(@car_park, CarParkPresenter) do |car_park| %>
    <div class="card m-1 border-secondary">
      <div class="text-end">
        <%= link_to "Back", ar_car_parks_path, class: 'btn btn-sm btn-secondary m-2', data: { turbo_frame: '_top' } %>
      </div>
      <dl class="row">
        <dt class="col-sm-5 text-end">Title</dt>
        <dd class="col-sm-7"><%= car_park.title %></dd>

        <dt class="col-sm-5 text-end">Address</dt>
        <dd class="col-sm-7"><%= car_park.address %></dd>

        <dt class="col-sm-5 text-end">Type</dt>
        <dd class="col-sm-7"><%= car_park.type %></dd>

        <dt class="col-sm-5 text-end">Usage fee</dt>
        <dd class="col-sm-7"><%= car_park.fee_currency_byn %></dd>

        <dt class="col-sm-5 text-end">Discount</dt>
        <dd class="col-sm-7"><%= car_park.discount_percentage %></dd>

        <dt class="col-sm-5 text-end">Spaces</dt>
        <dd class="col-sm-7"><%= car_park.spaces %></dd>
      </dl>
    </div>

    <div class="bg-body card m-1">
      <h3 class="text-center">Comments</h3>
      <%= render partial: 'comments/form', locals: { comment: Comment.new, commentable: car_park } %>
      <%= turbo_stream_from car_park, :comments %>
      <%= tag.div id: "#{(dom_id(car_park))}_comments" do %>
        <%= render partial: "comments/comment_with_replies", collection: car_park.comments.where(parent_id: nil), as: :comment %>
      <% end %>
    </div>

  <% end %>
<% end %>

app/views/car_parks/update.turbo_stream.erb
<%= turbo_stream.replace(@car_park, partial: 'owner_car_park', locals: { parking: @car_park }) %>
<%= turbo_stream.prepend('flash', partial: 'shared/flash') %>